services:
  postgres:
    image: postgres:16-alpine
    container_name: emps-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: emps_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - emps_postgres:/var/lib/postgresql/data

volumes:
  emps_postgres:
